routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['prefix'=>'admin','middleware'=>'auth'],function (){
    Route::get('/', 'AdminController@index')->name('admin');
    Route::group(['middleware' => ['role:Superadmin']], function () {
        Route::resource('users', 'UserController');
        Route::get('roles','UserController@roles')->name('roles');
        Route::post('roles','UserController@setRoles')->name('setRoles');
        Route::get('permissions','UserController@permissions')->name('permissions');
        Route::post('permissions','UserController@setPermissions')->name('setPermissions');
        Route::get('register','Auth\RegisterController@create')->name('register');
    });
    Route::resource('bills', 'BillController');
    Route::resource('categories', 'CategoryController');
    Route::resource('images', 'ImageController');
    Route::resource('products', 'ProductController');
});

Route::get('/get-products', 'HomeController@getProducts');
Route::get('/get-categories', 'HomeController@getCategories');
Route::get('/get-product/{product}', 'HomeController@getProduct');
Route::get('/get-products-by-category/{category}', 'HomeController@getProductsByCategory');

Route::get('/{vue_capture?}', function () {
    return view('welcome');
})->where('vue_capture', '[\/\w\.-]*');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'status',
    ];

    public function products()
    {
        return $this->belongsToMany('App\Product');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id','ASC')->paginate(10);
        return view('admin.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = Category::create($request->all());
        return redirect()->route('categories.index', $category->id)
            ->with('info', 'Categoría creada con éxito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        if($request->status){
            $category->status = 1;
        }else{
            $category->status = 0;
        }
        $category->name = $request->name;
        $category->description = $request->description;
        $category->save();
        return redirect()->route('categories.index', $category->id)
            ->with('info', 'Categoría actualizada con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->status = false;
        $category->save();
        return redirect()->route('categories.index')
            ->with('info', 'Categoría actualizada con éxito.');
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Categorías</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Categorías</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Agregar Categorías</div>
                    <div class="card-body">
                        {!! Form::open(['route'=>'categories.store']) !!}
                            <div class="form-group">
                                {{Form::label('name','Nombre')}}
                                {{Form::text('name',null,['class'=>'form-control', 'id'=>'name'])}}
                            </div>
                            <div class="form-group">
                                {{Form::label('description','Descripción')}}
                                {{Form::text('description',null,['class'=>'form-control', 'id'=>'description'])}}
                            </div>
                            <div class="form-check form-check-inline">
                                {{Form::checkbox('status', true, ['class'=>'form-check-input', 'id'=>'status'])}}
                                {{Form::label('status','Activo', ['class'=>'form-check-label'])}}
                            </div>
                            <div class="form-group">
                                {{Form::submit('Guardar',['class'=>'btn btn-primary'])}}
                                <a href="{{route('categories.index')}}" class="btn btn-default">Cancelar</a>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Categorías</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active"><a href="{{route('categories.index')}}">Categorías</a></li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Editar Categorías</div>
                    <div class="card-body">
                        {!! Form::model($category,['route'=>['categories.update', $category->id],'method'=>'PUT']) !!}
                        <div class="form-group">
                            {{Form::label('name','Nombre')}}
                            {{Form::text('name',null,['class'=>'form-control', 'id'=>'name'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('description','Descripción')}}
                            {{Form::text('description',null,['class'=>'form-control', 'id'=>'description'])}}
                        </div>
                        <div class="form-check form-check-inline">
                            {{Form::checkbox('status',1,null, ['class'=>'form-check-input', 'id'=>'status'])}}
                            {{Form::label('status','Activo', ['class'=>'form-check-label'])}}
                        </div>
                        <div class="form-group">
                            {{Form::submit('Guardar',['class'=>'btn btn-primary'])}}
                            <a href="{{route('categories.index')}}" class="btn btn-default">Cancelar</a>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Categorías</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Categorías</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Categorías <span class="float-right"><a href="{{route('categories.create')}}" class="btn btn-default btn-sm btn-circle" title="Agregar categoría">Agregar <i class="fa fa-plus"></i></a></span></div>
                    <div class="card-body">
                        <table class="table table-striped table-hover">
                            <thead>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Estado</th>
                            <th colspan="2"></th>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{$category->id}}</td>
                                    <td>{{$category->name}}</td>
                                    <td>{{$category->description}}</td>
                                    <td>
                                        @if($category->status)
                                            <span class="badge badge-success">Activo</span>
                                        @else
                                            <span class="badge badge-danger">Inactivo</span>
                                        @endif
                                    </td>
                                    <td><a href="{{route('categories.edit',['id'=>$category->id])}}" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></a></td>
                                    <td>
                                        {!! Form::open(['route'=>['categories.destroy', $category->id],'method'=>'DELETE','class'=>'delete-form']) !!}
                                        <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{$categories->render()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection