routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['prefix'=>'admin','middleware'=>'auth'],function (){
    Route::get('/', 'AdminController@index')->name('admin');
    Route::group(['middleware' => ['role:Superadmin']], function () {
        Route::resource('users', 'UserController');
        Route::get('roles','UserController@roles')->name('roles');
        Route::post('roles','UserController@setRoles')->name('setRoles');
        Route::get('permissions','UserController@permissions')->name('permissions');
        Route::post('permissions','UserController@setPermissions')->name('setPermissions');
        Route::get('register','Auth\RegisterController@create')->name('register');
    });
    Route::resource('bills', 'BillController');
    Route::resource('categories', 'CategoryController');
    Route::resource('images', 'ImageController');
    Route::resource('products', 'ProductController');
});

Route::get('/get-products', 'HomeController@getProducts');
Route::get('/get-categories', 'HomeController@getCategories');
Route::get('/get-product/{product}', 'HomeController@getProduct');
Route::get('/get-products-by-category/{category}', 'HomeController@getProductsByCategory');

Route::get('/{vue_capture?}', function () {
    return view('welcome');
})->where('vue_capture', '[\/\w\.-]*');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'price', 'status', 'stock', 'imei', 'code', 'external_link',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'status',
    ];

    public function bills()
    {
        return $this->belongsToMany('App\Bill');
    }
    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }
    public function images()
    {
        return $this->hasMany('App\Image');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Image;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id','ASC')->with('categories')->paginate(10);
//        dd($products);
        return view('admin.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('name','ASC')->pluck('name','id');
        return view('admin.product.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = Product::create($request->all());
        if($request->file('images')){
            $files = $request->file('images');
            $destinationPath = 'images';
            $images = [];
            foreach($files as $file) {
                $filename = $file->getClientOriginalName();
                $images[] = new Image(['description'=>$product->name,'url'=>$filename,'status'=>true]);
                $upload_success = $file->move($destinationPath, $filename);
            }
            $product->images()->saveMany($images);
        }
        foreach ($request->category_id as $id){
            $product->categories()->attach($id);
        }
        return redirect()->route('products.index')
            ->with('info', 'Producto creado correctamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $product->load('images');
        return view('admin.product.show',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::orderBy('name','ASC')->pluck('name','id');
        $product->load('categories');
        return view('admin.product.edit',compact('categories','product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        if($request->status){
            $product->status = 1;
        }else{
            $product->status = 0;
        }
        $product->name = $request->name;
        $product->description = $request->description;
        $product->price = $request->price;
        $product->stock = $request->stock;
        $product->imei = $request->imei;
        $product->code = $request->code;
        $product->categories()->detach();
        foreach ($request->category_id as $id){
            if(!$product->categories()->find($id)) {
                $product->categories()->attach($id);
            }
        }
        if($request->file('images')){
            $files = $request->file('images');
            $destinationPath = 'images';

            $images = [];
            foreach($files as $file) {
                $filename = $file->getClientOriginalName();
                $images[] = new Image(['description'=>$product->name,'url'=>$filename,'status'=>true]);
                $upload_success = $file->move($destinationPath, $filename);
            }

            $product->images()->saveMany($images);
        }
        $product->external_link = $request->external_link;
        $product->save();
        return redirect()->route('products.index', $product->id)
            ->with('info', 'Producto actualizado con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->status = false;
        $product->save();
        return redirect()->route('products.index')
            ->with('info', 'Producto eliminado correctamente');
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Productos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active"><a href="{{route('products.index')}}">Productos</a></li>
                    <li class="breadcrumb-item active">Agregar</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Agregar Producto</div>
                    <div class="card-body">
                        {!! Form::open(['route'=>'products.store', 'files'=> true]) !!}
                        @include('admin.product.partials.form')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Productos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active"><a href="{{route('products.index')}}">Productos</a></li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Editar Producto</div>
                    <div class="card-body">
                        {!! Form::model($product,['route'=>['products.update', $product->id],'method'=>'PUT','files'=>true]) !!}
                        @include('admin.product.partials.form')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Productos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Productos</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Cantidad: <span class="small">{{count($products)}}</span>
                        <span class="float-right">
                            <a href="{{route('products.create')}}" class="btn btn-default btn-sm btn-circle" title="Agregar producto">
                                Agregar
                                <i class="fa fa-plus"></i>
                            </a>
                        </span>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover">
                            <thead>
                            <th>ID</th>
                            <th>Nombre</th>
                            {{--<th>Descripción</th>--}}
                            <th>Precio</th>
                            <th>Stock</th>
                            <th>IMEI</th>
                            <th>Código</th>
                            <th>Estado</th>
                            <th>Categoría</th>
                            <th></th>
                            </thead>
                            <tbody>
                            @foreach($products as $product)
                                <tr>
                                    <td>{{$product->id}}</td>
                                    <td>{{$product->name}}</td>
{{--                                    <td>{{$product->description}}</td>--}}
                                    <td>{{$product->price}}</td>
                                    <td>{{$product->stock}}</td>
                                    <td>{{$product->imei}}</td>
                                    <td>{{$product->code}}</td>
                                    <td>
                                        @if($product->status)
                                            <span class="badge badge-success">Activo</span>
                                        @else
                                            <span class="badge badge-danger">Inactivo</span>
                                        @endif
                                    </td>
                                    <td>
                                        @foreach($product->categories as $category)
                                            {{$category->name}}
                                        @endforeach
                                    </td>
                                    <td>
                                        <a href="{{route('products.edit',$product->id)}}" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></a>
                                        <a href="{{route('products.show',$product->id)}}" class="btn btn-sm btn-default"><i class="fa fa-image"></i></a>
                                        {!! Form::open(['route'=>['products.destroy', $product->id],'method'=>'DELETE','class'=>'delete-form']) !!}
                                        <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{$products->render()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/product/show.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Productos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Productos</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Imagenes de {{$product->name}}
                    </div>
                    <div class="card-body">
                        <div class="row">
                            @foreach($product->images as $image)
                                <div class="col-4 bg-white">
                                    <img src="{{asset('/images/'.$image->url)}}" alt="{{$image->description}}" class="img-fluid see-img" onclick="verImagen(this)">
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Modal body text goes here.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        var seeImg = document.getElementsByClassName('see-img');
        console.log(seeImg);
        for (var i = 0; i < seeImg.length; i++) {
            seeImg[i].style.cursor = 'pointer';
        }
        function verImagen(e){
            console.log(e);
            $('.modal-header').html(e.alt);
            $('.modal-body').html('<img src="'+e.src+'" alt="'+e.alt+'" class="img-fluid see-img">');
            $('.modal').modal('show');
        }
    </script>
@endsection