routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['prefix'=>'admin','middleware'=>'auth'],function (){
    Route::get('/', 'AdminController@index')->name('admin');
    Route::group(['middleware' => ['role:Superadmin']], function () {
        Route::resource('users', 'UserController');
        Route::get('roles','UserController@roles')->name('roles');
        Route::post('roles','UserController@setRoles')->name('setRoles');
        Route::get('permissions','UserController@permissions')->name('permissions');
        Route::post('permissions','UserController@setPermissions')->name('setPermissions');
        Route::get('register','Auth\RegisterController@create')->name('register');
    });
    Route::resource('bills', 'BillController');
    Route::resource('categories', 'CategoryController');
    Route::resource('images', 'ImageController');
    Route::resource('products', 'ProductController');
});

Route::get('/get-products', 'HomeController@getProducts');
Route::get('/get-categories', 'HomeController@getCategories');
Route::get('/get-product/{product}', 'HomeController@getProduct');
Route::get('/get-products-by-category/{category}', 'HomeController@getProductsByCategory');

Route::get('/{vue_capture?}', function () {
    return view('welcome');
})->where('vue_capture', '[\/\w\.-]*');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Spatie\Permission\Exceptions\PermissionAlreadyExists;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id','ASC')->paginate();
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating new User.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        /*if (! Gate::allows('users_manage')) {
            return abort(401);
        }*/
        $roles = Role::get()->pluck('name', 'name');

        return view('admin.user.create', compact('roles'));
    }
    /**
     * Store a newly created User in storage.
     *
     * @param  \App\Http\Requests\StoreUsersRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*if (! Gate::allows('users_manage')) {
            return abort(401);
        }*/
        $user = User::create($request->all());
        $user->password = bcrypt($request->password);
        $user->save();
        $roles = $request->input('roles') ? $request->input('roles') : [];
        $user->assignRole($roles);

        return redirect()->route('users.index');
    }

    public function show(User $user){
        $user->load(['permissions','roles']);
        return view('admin.user.show',compact('user'));
    }

    //Roles y permisos

    public function roles(){
        $roles = Role::all();
        return view('admin.user.role',compact('roles'));
    }

    public function setRoles(Request $request){
        if($request->name!=null){
            $role = Role::create(['name' => $request->name,'status'=>1]);
        }
        return redirect()->route('roles', compact('role'))
            ->with('info', 'Entrada creada con éxito.');
    }

    public function permissions(){
        $permissions = Permission::all();
        $roles = Role::orderBy('name','ASC')->pluck('name','id');
        return view('admin.user.permission',compact('permissions','roles'));
    }

    public function setPermissions(Request $request){
        try{
            $permission = Permission::create(['name' => $request->name,'status'=>1]);
            $role = Role::findById($request->role_id);
            $permission->assignRole($role);
            return redirect()->route('permissions', compact('permission'))
                ->with('info', 'Entrada creada con éxito.');
        }catch (PermissionAlreadyExists $e){
            return redirect()->route('permissions')
                ->with('error', 'Ya existe un permiso con ese nombre.');
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Usuarios</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Usuarios</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Agregar Usuario</div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('users.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                                </div>
                            </div>

                            <div class="form-group">
                                {!! Form::label('roles', 'Roles*', ['class' => 'control-label']) !!}
                                {!! Form::select('roles[]', $roles, old('roles'), ['class' => 'form-control select2', 'multiple' => 'multiple', 'required' => '']) !!}
                                <p class="help-block"></p>
                                @if($errors->has('roles'))
                                    <p class="help-block">
                                        {{ $errors->first('roles') }}
                                    </p>
                                @endif
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                {{--<h1 class="m-0 text-dark">Usuarios</h1>--}}
                <nav class="navbar navbar-expand-lg navbar-light bg-white">
                    <a class="navbar-brand" href="#">Usuarios</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('users.create')}}">Nuevo</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('roles')}}">Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('permissions')}}">Permisos</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Usuarios</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Usuarios</div>
                    <div class="card-body">
                        <table class="table table-striped table-hover">
                            <thead>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Correo electrónico</th>
                            <th>Roles</th>
                            <th>Estado</th>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{$user->id}}</td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>
                                        @foreach($user->getRoleNames() as $role)
                                            {{$role}}
                                        @endforeach
                                    </td>
                                    <td>
                                        @if($user->status)
                                            <span class="badge badge-success">Activo</span>
                                        @else
                                            <span class="badge badge-danger">Inactivo</span>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{$users->render()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/permission.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Permisos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Permisos</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Agregar Permisos</div>
                    <div class="card-body">
                        {!! Form::open(['route'=>'setPermissions']) !!}
                        <div class="form-group">
                            {{Form::label('name','Nombre')}}
                            {{Form::text('name',null,['class'=>'form-control', 'id'=>'name'])}}
                        </div>
                        <div class="form-group">
                            {{ Form::label('role_id','Role') }}
                            {{ Form::select('role_id',$roles,null,['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{Form::submit('Guardar',['class'=>'btn btn-primary'])}}
                            <a href="{{route('categories.index')}}" class="btn btn-default">Cancelar</a>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Permisos</div>
                    <div class="card-body">
                        <table class="table table-hover table-striped">
                            <thead>
                            <th>Name</th>
                            </thead>
                            <tbody>
                            @foreach($permissions as $permission)
                                <tr>
                                    <td>{{$permission->name}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/role.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Roles</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Roles</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Agregar Roles</div>
                    <div class="card-body">
                        {!! Form::open(['route'=>'setRoles']) !!}
                        <div class="form-group">
                            {{Form::label('name','Nombre')}}
                            {{Form::text('name',null,['class'=>'form-control', 'id'=>'name'])}}
                        </div>
                        <div class="form-group">
                            {{Form::submit('Guardar',['class'=>'btn btn-primary'])}}
                            <a href="{{route('categories.index')}}" class="btn btn-default">Cancelar</a>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Roles</div>
                    <div class="card-body">
                        <table class="table table-hover table-striped">
                            <thead>
                            <th>Name</th>
                            </thead>
                            <tbody>
                            @foreach($roles as $rol)
                                <tr>
                                    <td>{{$rol->name}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Usuarios</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Usuarios</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Agregar Usuario</div>
                    <div class="card-body">
                        <p><strong>Nombre de usuario:</strong> {{$user->name}}</p>
                        <p><strong>Correo electrónico de usuario:</strong> {{$user->email}}</p>
                        <p>
                            <strong>Roles del usuario:</strong>
                            @foreach($user->roles as $role)
                                {{$role->name}}
                            @endforeach
                        </p>
                        <p>
                            <strong>Permisos del usuario:</strong>
                            @foreach($user->permissions as $permission)
                                {{$permission->name}}
                            @endforeach
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection